apiVersion: apps/v1
kind: Deployment
metadata:
  name: website12-deployment
  labels:
    app: website12
spec:
  replicas: 3   # Number of desired replicas
  selector:
    matchLabels:
      app: website12
  template:
    metadata:
      labels:
        app: website12
    spec:
      containers:
      - name: website12
        image: haydenpal2003/website12:tagname  # Updated Docker image name and tag
        ports:
        - containerPort: 80  # Port your application listens on

---
apiVersion: v1
kind: Service
metadata:
  name: website12-service
  labels:
    app: website12
spec:
  type: LoadBalancer
  ports:
    - port: 80  # Port to expose on the service
      targetPort: 80  # Port your application listens on in the pods
  selector:
    app: website12
